### ISSUE TITLE
Filter results from plugins

### ISSUE THREAD

**Issue by thsutton** [anchor/git-vogue#56]
Some checks will report items which can't be resolved. Cabal, for instance, reports:

> 'ghc-options: -O2' is rarely needed. Check that it is giving a real benefit
> and not just imposing longer compile times on your users.

whenever `-O2` is present. If you *have* checked, it'd be nice to be able to filter this warning out.

**Comment by thsutton** [comment]
Noted by @fractalcat

**Comment by christian-marie** [comment]
Yeah... we certainly should be able to. It's annoying that cabal does that though.
