### ISSUE TITLE
Checks get sad in repos which have packages in subdirs

### ISSUE THREAD

**Issue by thsutton** [anchor/git-vogue#61]
https://github.com/anchor/oauth2-server contains two packages, each in a subdirectory. I generally make a sandbox at the top level and "cabal sandbox add-source *".

This seems to make the checks sad:

- `git-vogue-cabal` can't find the cabal files.
- `git-vogue-ghc-mod` reports "Could not find module" when `cabal repl` can do it perfectly fine.

The first is definitely due to the subdirs thing; maybe the ghc-mod thing is too?

**Comment by christian-marie** [comment]
Not sure how to fix this.

**Comment by thsutton** [comment]
Maybe search for *.cabal files and run `cabal check` in the appropriate directory? Unless anyone has changed it since I created it `git-vogue-cabal` just executes `cabal check` in the git repo root.

**Comment by christian-marie** [comment]
Fixed in master.
