### ISSUE TITLE
no plugins listed after installation

### ISSUE THREAD

**Issue by rbtcollins** [anchor/git-vogue#80]
git vogue plugins
git-vogue looks for plugins in:

        /home/robertc/.cabal/libexec/git-vogue

git-vogue knows about the following plugins:

robertc@lifeless-z140:~/personal/haskell/scratchpad$ ls /home/robertc/.cabal/libexec/git-vogue
ls: cannot access /home/robertc/.cabal/libexec/git-vogue: No such file or directory

**Comment by tvh** [comment]
I assume you are using cabal 1.18? In that version is a bug, where `copyHook` is not called. https://github.com/haskell/cabal/issues/1805.

**Comment by rbtcollins** [comment]
I was; is it possible to make git-vogue error if built by cabal 1.18?

**Comment by thsutton** [comment]
@rbtcollins You can probably do the following to work around the bug in Cabal:

````
mkdir -p /home/robertc/.cabal/libexec/git-vogue
mv /home/robertc/.cabal/bin/git-vogue-* /home/robertc/.cabal/libexec/git-vogue/
````

Alternatively, you can defined the `GIT_VOGUE_PATH` environmental variable by adding something like this to your shell config:

````
export GIT_VOGUE_PATH="$HOME/.cabal/bin"
````

**Comment by thsutton** [comment]
Actually, you probably shouldn't use `GIT_VOGUE_PATH`. I think it'll try to use all the executable files as plugins.

**Comment by christian-marie** [comment]
@rbtcollins Still need to address your suggestion and see if we can bail out/print some kind of help if the installation fails. Perhaps we could also detect if the libexec dir does not exist, and print a suggestion.
