### ISSUE TITLE
ghc-mod check succeeds on error

### ISSUE THREAD

**Issue by fractalcat** [anchor/git-vogue#81]
```
ghc-mod check succeeded with:
GMEIOException /home/sio/src/borel/dist/setup-config: hGetContents: invalid argument (invalid byte sequence)
Checked 1 file(s)
```
Seems like this probably shouldn't result in a successful exit status?

**Comment by thsutton** [comment]
That's "cabal and ghc and ghc-mod aren't talking right now". Probably shouldn't be a git-vogue error as it has nothing to do with the code in the repo (and everything to do with your cabal/cabal-install being too new).

**Comment by fractalcat** [comment]
Alright, if this is expected behavior I won't worry about it.

**Comment by christian-marie** [comment]
Should help the user out with the explain function.
